server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库其他配置
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

# 注册服务到 eureka service
eureka:
#  instance:
#    preferIpAddress: true
#  instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    # true eureka client 需要注册
    register-with-eureka: true
    # true 是否从 Eureka Server 抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    serviceUrl:
      # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka #,http://localhost:7002/eureka # 集群

mybatis:
  mapper-locations: classpath*:/mybatis/*Mapper.xml