server:
  port: 7001

spring:
  application:
    name: cloud-eureka-server


eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30 #心跳时间
    lease-expiration-duration-in-seconds: 90 #最后一次心跳后等待时间上限，默认90s
  client:
    # false 表示不注册自己
    register-with-eureka: false
    # false 表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false # 禁用自我保护机制
    eviction-interval-timer-in-ms: 2000 # 微服务保持的心跳超过就删除