server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_nomal_routh  # 路由的id，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-PAYMENT # 匹配后提供服务的路由地址
          filters:
            - AddRequestParameter=X-Reques-ID,1024
          predicates:
            - Path=/payment/get/**  # 断言，路径匹配的进行路由

        - id: payment_nomal_routh2  # 路由的id，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-PAYMENT # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/uuid/**  # 断言，路径匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka
